// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atenbyftllayblozqhqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0ZW5ieWZ0bGxheWJsb3pxaHFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5NzM4MTcsImV4cCI6MjA2MDU0OTgxN30.LnKxAS0kXAvaqqGmlQpxBW9LIsgS0jVkqfMqnLfg12k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);